-- Idea Lab anonymous usage events.
-- Safe to re-run: every statement is idempotent.

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  anonymous_id uuid not null,
  event_name text not null check (event_name in ('generate', 'save', 'unsave', 'copy', 'explore', 'refine', 'rating', 'share')),
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.usage_events enable row level security;

-- PostgreSQL has no `jsonb_object_length`, so key counting needs a helper.
-- Wrapping it in an immutable function also keeps the policy expression simple.
create or replace function public.jsonb_key_count(data jsonb)
returns integer
language sql
immutable
parallel safe
as $$ select count(*)::int from jsonb_object_keys(data) $$;

-- Browser clients may only append events. No select/update/delete policy exists,
-- so the anon role cannot read anything back out of this table.
drop policy if exists "anonymous events can be inserted" on public.usage_events;

create policy "anonymous events can be inserted"
on public.usage_events for insert
to anon
with check (
  jsonb_typeof(properties) = 'object'
  and public.jsonb_key_count(properties) <= 8
  and event_name in ('generate', 'save', 'unsave', 'copy', 'explore', 'refine', 'rating', 'share')
);

grant insert on table public.usage_events to anon;

create index if not exists usage_events_created_at_idx on public.usage_events (created_at desc);
create index if not exists usage_events_event_name_idx on public.usage_events (event_name);
