-- Idea Lab schema: anonymous usage events, user profiles, trial credits, billing.
-- Safe to re-run: every statement is idempotent.

-- ============================================================================
-- 1. Anonymous usage events
-- ============================================================================

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  anonymous_id uuid not null,
  event_name text not null,
  properties jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.usage_events enable row level security;

-- PostgreSQL has no `jsonb_object_length`, so key counting needs a helper.
-- Wrapping it in an immutable function also keeps the policy expression simple.
create or replace function public.jsonb_key_count(data jsonb)
returns integer
language sql
immutable
parallel safe
as $$ select count(*)::int from jsonb_object_keys(data) $$;

-- The event-name allowlist grows with the app (v2 adds signal + blueprint
-- events), so any existing check constraint — named or unnamed — is dropped
-- first and replaced with the extended one below.
do $$
declare
  constraint_record record;
begin
  for constraint_record in
    select conname from pg_constraint
    where conrelid = 'public.usage_events'::regclass and contype = 'c'
  loop
    execute format('alter table public.usage_events drop constraint %I', constraint_record.conname);
  end loop;
end $$;

alter table public.usage_events
  add constraint usage_events_event_name_check
  check (event_name in (
    'generate', 'save', 'unsave', 'copy', 'explore', 'refine', 'rating', 'share',
    'signals_scan', 'signals_forge', 'blueprint', 'upgrade'
  ));

-- Browser clients may only append events. No select/update/delete policy exists,
-- so the anon role cannot read anything back out of this table.
drop policy if exists "anonymous events can be inserted" on public.usage_events;

create policy "anonymous events can be inserted"
on public.usage_events for insert
to anon
with check (
  jsonb_typeof(properties) = 'object'
  and public.jsonb_key_count(properties) <= 8
  and event_name in (
    'generate', 'save', 'unsave', 'copy', 'explore', 'refine', 'rating', 'share',
    'signals_scan', 'signals_forge', 'blueprint', 'upgrade'
  )
);

grant insert on table public.usage_events to anon;

create index if not exists usage_events_created_at_idx on public.usage_events (created_at desc);
create index if not exists usage_events_event_name_idx on public.usage_events (event_name);

-- ============================================================================
-- 2. User profiles, free trial credits, and billing state
-- ============================================================================

-- Trial policy: every new account starts on the 'trial' plan with a fixed
-- number of free metered actions. When the credits run out the account drops
-- to 'free' (no metered access) until they subscribe, which flips plan to
-- 'pro' via the Stripe webhook. All credit/plan mutations happen server-side
-- with the service role; users get read-only access to their own row.

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text,
  display_name text,
  plan text not null default 'trial' check (plan in ('trial', 'free', 'pro')),
  trial_scans_left integer not null default 5,
  trial_ai_left integer not null default 3,
  stripe_customer_id text,
  subscription_status text not null default 'none',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

-- Users can read their own profile (plan + remaining credits drive the UI).
drop policy if exists "profiles are readable by owner" on public.profiles;
create policy "profiles are readable by owner"
on public.profiles for select
to authenticated
using (auth.uid() = id);

-- Fallback self-service creation for deployments where the auth trigger below
-- has not run yet (e.g. the schema was applied after the first signup). The
-- check forces stock defaults, so a self-created row can never grant itself
-- 'pro' or extra credits.
drop policy if exists "profiles can be self-created with defaults" on public.profiles;
create policy "profiles can be self-created with defaults"
on public.profiles for insert
to authenticated
with check (
  auth.uid() = id
  and plan = 'trial'
  and trial_scans_left = 5
  and trial_ai_left = 3
  and subscription_status = 'none'
  and stripe_customer_id is null
);

-- No update/delete policies: plan and credit changes must go through the
-- service role (API functions + webhook), which bypasses RLS.
revoke update, delete on public.profiles from anon, authenticated;
grant select, insert on public.profiles to authenticated;

-- Mirror every new auth user into a profile so the trial is available on the
-- very first sign-in, even before the client ever loads.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'full_name', split_part(new.email, '@', 1))
  )
  on conflict (id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

-- ============================================================================
-- 3. Atomic trial credit accounting
-- ============================================================================

-- Consumes one trial credit ('scan' or 'ai') in a single atomic statement.
-- Returns the updated plan/credit snapshot, or null when the user has no
-- profile, is out of that credit, or is not on the trial plan (pro access is
-- checked separately before this is called).
create or replace function public.consume_trial_credit(p_user uuid, p_kind text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if p_kind not in ('scan', 'ai') then
    raise exception 'p_kind must be ''scan'' or ''ai''';
  end if;

  update public.profiles
     set trial_scans_left = case when p_kind = 'scan' then trial_scans_left - 1 else trial_scans_left end,
         trial_ai_left = case when p_kind = 'ai' then trial_ai_left - 1 else trial_ai_left end,
         updated_at = now()
   where id = p_user
     and plan = 'trial'
     and (case when p_kind = 'scan' then trial_scans_left > 0 else trial_ai_left > 0 end)
  returning jsonb_build_object(
    'plan', plan,
    'trial_scans_left', trial_scans_left,
    'trial_ai_left', trial_ai_left,
    'subscription_status', subscription_status
  ) into result;

  return result;
end $$;

-- Restores a credit when a metered action failed for reasons the user could
-- not control (e.g. the model provider errored after the credit was taken).
create or replace function public.refund_trial_credit(p_user uuid, p_kind text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_kind not in ('scan', 'ai') then
    raise exception 'p_kind must be ''scan'' or ''ai''';
  end if;

  update public.profiles
     set trial_scans_left = case when p_kind = 'scan' then trial_scans_left + 1 else trial_scans_left end,
         trial_ai_left = case when p_kind = 'ai' then trial_ai_left + 1 else trial_ai_left end,
         updated_at = now()
   where id = p_user
     and plan = 'trial';
end $$;

revoke execute on function public.consume_trial_credit(uuid, text) from public, anon, authenticated;
revoke execute on function public.refund_trial_credit(uuid, text) from public, anon, authenticated;
grant execute on function public.consume_trial_credit(uuid, text) to service_role;
grant execute on function public.refund_trial_credit(uuid, text) to service_role;

create index if not exists profiles_stripe_customer_idx on public.profiles (stripe_customer_id);
